# ----------- CONFIGURABLE START -----------
title:            "Yven's Blog"
description:      "less more"
url:              https://fangyang.me # Site url, without a slash at the end.
signoff:          "yven" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons

links:
  - name:         Contents
    url:          /
    external:     false
  - name:         About me
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

permalink:        /blog/:title
defaults:
  - values:
      layout: "default"
